import os

SECRET_KEY = os.environ.get('SECRET_KEY')
FOOTBALL_DATA_API_KEY = os.environ.get('FOOTBALL_DATA_API_KEY')
FOOTBALL_DATA_API_URL = os.environ.get('FOOTBALL_DATA_API_URL')
X_CONSUMER_KEY = os.environ.get('X_CONSUMER_KEY')
X_CONSUMER_SECRET = os.environ.get('X_CONSUMER_SECRET')
X_ACCESS_TOKEN = os.environ.get('X_ACCESS_TOKEN')
X_ACCESS_TOKEN_SECRET = os.environ.get('X_ACCESS_TOKEN_SECRET')
X_BEARER_TOKEN = os.environ.get('X_BEARER_TOKEN')

HEADERS = {'X-Auth-Token': FOOTBALL_DATA_API_KEY}
